apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cikl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0001-tenant/tkrw-pr712-0075-0001-app/devfile-sample-cikl@sha256:fa5728dbd273ed40e0cfbbba767bc092232b1ff034093985da3097403dc6aad2
        name: my-nodejs
        resources: {}
status: {}
